### ISSUE TITLE
Errors opening files (including DZG)

### ISSUE THREAD

**Issue by pwernette** [iannesbitt/readgssi#30]
When trying to run the help or open a DZT file I keep getting the following error:
`$ readgssi -h
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\readgssi\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\readgssi\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\readgssi\Scripts\readgssi.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\readgssi\lib\site-packages\readgssi\readgssi.py", line 275, in main
    fx.printmsg(config.help_text)
  File "c:\programdata\anaconda3\envs\readgssi\lib\site-packages\readgssi\functions.py", line 12, in printmsg
    print('%s - %s' % (datetime.now().strftime('%Y-%m-%d %H:%M:%S'), msg))
  File "c:\programdata\anaconda3\envs\readgssi\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f12f' in position 134: character maps to <undefined>
`

**Comment by iannesbitt** [comment]
@pwernette instead of GitBash, can you try running `readgssi -h` in an Anaconda Prompt?
