### ISSUE TITLE
Multi-frequency antenna, header problem

### ISSUE THREAD

**Issue by alecomunian** [iannesbitt/readgssi#33]
Hello, there seems to be a problem when reading multi channel *.DZT files from a GSSI SIR4000 console, with a multi frequency antenna 300MHz/800MHz. It looks like in their header file they do not separate properly the info related to the different channels. It is already somehow buggy in the way it looks on RADAN.

From the command line, I use:

`readgssi -N -f gprpy -i CAV_2Z2-01__001.DZT`

(input file attached as a ZIP file
[CAV_2Z2-01__001.zip](https://github.com/iannesbitt/readgssi/files/5941918/CAV_2Z2-01__001.zip)
)

Hereinafter the WARNING messages and the error:

```
...
--------------------WARNING - PLEASE READ---------------------
2021-02-08 08:10:30 - WARNING: could not read frequency for antenna name "'300/800D'"
2021-02-08 08:10:30 - WARNING: trying to use frequencies of None MHz (estimated)...
2021-02-08 08:10:30 - more info: rh_ant=['300/800D', 'none', None, None]
2021-02-08 08:10:30 -            known_ant=[False, False, None, None]
2021-02-08 08:10:30 - please submit a bug report with this warning, the antenna name and frequency
2021-02-08 08:10:30 - at https://github.com/iannesbitt/readgssi/issues/new
2021-02-08 08:10:30 - or send via email to ian (dot) nesbitt (at) gmail (dot) com.
2021-02-08 08:10:30 - if possible, please attach a ZIP file with the offending DZT inside.
--------------------------------------------------------------
--------------------WARNING - PLEASE READ---------------------
2021-02-08 08:10:30 - WARNING: could not read frequency for antenna name "'none'"
2021-02-08 08:10:30 - WARNING: trying to use frequencies of None MHz (estimated)...
2021-02-08 08:10:30 - more info: rh_ant=['300/800D', 'none', None, None]
2021-02-08 08:10:30 -            known_ant=[False, False, None, None]
2021-02-08 08:10:30 - please submit a bug report with this warning, the antenna name and frequency
2021-02-08 08:10:30 - at https://github.com/iannesbitt/readgssi/issues/new
2021-02-08 08:10:30 - or send via email to ian (dot) nesbitt (at) gmail (dot) com.
2021-02-08 08:10:30 - if possible, please attach a ZIP file with the offending DZT inside.
--------------------------------------------------------------
2021-02-08 08:10:30 - beginning processing for channel 0 (antenna 300/800D)
2021-02-08 08:10:30 - no gps information for distance normalization
Traceback (most recent call last):
  File "/home/alex/.virtualenvs/gpr/bin/readgssi", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.virtualenvs/gpr/lib/python3.8/site-packages/readgssi/readgssi.py", line 480, in main
    readgssi(infile=infile, outfile=outfile, antfreq=antfreq, frmt=frmt, plotting=plotting, dpi=dpi,
  File "/home/alex/.virtualenvs/gpr/lib/python3.8/site-packages/readgssi/readgssi.py", line 146, in readgssi
    header, data[ar], gps = arrayops.distance_normalize(header=header, ar=data[ar], gps=gps,
  File "/home/alex/.virtualenvs/gpr/lib/python3.8/site-packages/readgssi/arrayops.py", line 162, in distance_normalize
    return header, proc, gps
UnboundLocalError: local variable 'proc' referenced before assignment


```
Sorry for bothering you with an issue which is probably related to a GSSI bug, and thank you again for your efforts!
Best,
Alessandro

**Comment by iannesbitt** [comment]
Hi @alecomunian, thank you for the report and my apologies for taking so long to address it. I had not seen this error before, and you are probably correct that it's a GSSI bug. I did manage to get some output from it however (see attached). You can try the commit referenced above and get the same result with the following:

```
readgssi -f gprpy -i CAV_2Z2-01__001.DZT -Z 0,0
```
Note that I leave out the `-N` since there is no associated GPS file to normalize to. If this data was collected with a survey wheel, the data should already be distance-normalized.

[CAV_2Z2-01__001-gprpy.zip](https://github.com/iannesbitt/readgssi/files/6965084/CAV_2Z2-01__001-gprpy.zip)
