### ISSUE TITLE
GPS reading, datetime error

### ISSUE THREAD

**Issue by GGDRriedel** [iannesbitt/readgssi#43]
Hey there. I am trying to use certain modules within python to read GPS data. 

I'm getting the following error : 

```
dzt.readdzt("TUK_MESSUNGEN_KATALOG_002.DZT")
2023-05-15 16:18:12 - WARNING: no time zero specified for channel 0, defaulting to rh_zero value (1)
2023-05-15 16:18:12 - WARNING: no time zero specified for channel 1, defaulting to rh_zero value (1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Riedel\.conda\envs\readgssi\lib\site-packages\readgssi\dzt.py", line 306, in readdzt
    gps = readdzg(infile_gps, 'dzg', header, verbose=verbose)
  File "C:\Users\Riedel\.conda\envs\readgssi\lib\site-packages\readgssi\gps.py", line 97, in readdzg
    ts0 = TZ.localize(datetime.combine(msg.datestamp, msg.timestamp)) # row 0's timestamp (not ideal)
  File "C:\Users\Riedel\.conda\envs\readgssi\lib\site-packages\pytz\__init__.py", line 245, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
```

According to this: 

https://github.com/celery/celery/issues/983

It seems to be a bug?

**Comment by iannesbitt** [comment]
Hi @GGDRriedel, this is due to a change in how `pytz` handles localization and should be fixed in readgssi version 0.0.22, which is on pip now. So `conda activate readgssi; pip install -U readgssi` should do it
